In [2]:
import numpy as np

In [3]:
arr = np.array([1,2,3])

In [4]:
arr

array([1, 2, 3])

In [5]:
np.zeros(3)

array([0., 0., 0.])

In [6]:
np.zeros((4,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [7]:
np.ones((5,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [9]:
np.arange(1, 10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
np.linspace(0, 5, 10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [11]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [12]:
np.random.rand(5)

array([0.30230671, 0.96015585, 0.49281026, 0.03788076, 0.78993121])

In [15]:
np.random.rand(4, 4)

array([[0.87417627, 0.14451329, 0.44732157, 0.6206275 ],
       [0.17873032, 0.36203368, 0.21182025, 0.53796519],
       [0.81058666, 0.31022712, 0.66223682, 0.02483822],
       [0.44678056, 0.47297021, 0.66465117, 0.66207542]])

In [16]:
np.random.randint(1, 100, 10)

array([31, 64,  7, 52, 52, 85, 84, 65, 49, 58])

In [17]:
arr = np.arange(25)

In [18]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [20]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [21]:
arr.max()

24

In [22]:
arr.argmax()

24

In [23]:
arr.argmin()

0

In [24]:
randarr = np.random.randint(0, 50, 10)

In [25]:
randarr

array([42, 30,  9, 11, 27, 15, 40, 20, 43, 46])

In [26]:
randarr.max()

46

In [27]:
randarr.argmax()

9

In [29]:
randarr.argmin()

2

In [30]:
randarr.dtype

dtype('int32')

In [31]:
arr.dtype

dtype('int32')

In [32]:
arr = np.arange(0,15)

In [33]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [34]:
arr[2:5]

array([2, 3, 4])

In [35]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [38]:
arr[0:2] = 10

In [39]:
arr

array([10, 10,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [41]:
arr = np.arange(0, 15)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [43]:
arr_copy = arr.copy()

In [44]:
arr_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [46]:
slice_arr_copy = arr_copy[0:5]

In [47]:
slice_arr_copy

array([0, 1, 2, 3, 4])

In [48]:
slice_arr_copy[:] = 88

In [49]:
slice_arr_copy

array([88, 88, 88, 88, 88])

In [50]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [51]:
arr_copy

array([88, 88, 88, 88, 88,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])